server:
  port: 12345

spring:
  application:
    name: customer service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:

logging:
  level:
    root: info
