

server:
  port: 12345

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example?serverTimezone=UTC&characterEncoding=utf-8
    password: 123456
    username: springuser

log4j:
  appender:
    stdout: org.apache.log4j.ConsoleAppender
    stdout.layout: org.apache.log4j.PatternLayout
    stdout.layout.ConversionPattern: '%5p [%t] - %m'
  rootLogger: ERROR, stdout
logging:
  level:
    com:
      junyi:
        helloworld:
          mapper: debug
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
